steps:
    - name: gcr.io/cloud-builders/docker
      args:
          - build
          - "--no-cache"
          - "-t"
          - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
          - "-f"
          - backend/Dockerfile
      id: Build

    - name: gcr.io/cloud-builders/docker
      args:
          - push
          - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
      id: Push

    - name: gcr.io/cloud-builders/docker
      args: [ compute, instances, update-container, thepit-backend, reset, --container-image="$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA", --container-privileged ]
      id: Deploy

      entrypoint: gcloud
timeout: 3600s
images:
    - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
